apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jbe-ho-erfa.fullname" . }}
  labels:
    {{- include "jbe-ho-erfa.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: {{ include "jbe-ho-erfa.fullname" . }}
            port:
              number: 8000
