apiVersion: v1
kind: Service
metadata:
  name: {{ include "jbe-ho-erfa.fullname" . }}
  labels:
    {{- include "jbe-ho-erfa.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jbe-ho-erfa.selectorLabels" . | nindent 4 }}
