[package]
name = "actix-test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.5"
log = "0.4.22"
mongodb = "3.1.0"
serde = { version = "1.0.210", features = ["derive"] }
uuid = { version = "1.10.0", features = ["fast-rng", "serde", "v4"] }
