resources:
  requests:
    cpu: 1
    memory: 500Mi
  limits:
    cpu: 1
    memory: 500Mi
env:
  - name: MONGODB_URI
    value: "mongodb://mongodb:27017"
image:
  repository: jklsuperuniqueregistry.azurecr.io/tests/actix
  tag: latest
service:
  port: 8080
