extraConfigMaps:
  locust-asset: /assets
loadtest:
  locust_locustfile_configmap: locustfile
  pip_packages:
    - pandas
worker:
  replicas: 4
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
